### ISSUE TITLE
Prevent warnings from array_flip using extbase extension parameters

### ISSUE THREAD

**Issue by heidenreichC** [sourcebroker/urlguard#1]
I get the following warning while calling a url with parameters like "?tx_ext_pi1[action]=Random":
> Warning: array_flip(): Can only flip STRING and INTEGER values! in .../ext/urlguard/Classes/Frontend/ContentObject/ContentObjectRenderer.php on line 75

Of course for productive usage I wouldn't display any errors or warnings but for development context I don't want to see any warnings because of parameters at all.

**Comment by kszymukowicz** [comment]
Please try version 0.2.0.
Should be fixed there.
