### ISSUE TITLE
Usage of arrayDiffAssocRecursive differs from TYPO3 versions

### ISSUE THREAD

**Issue by heidenreichC** [sourcebroker/urlguard#2]
I can't use the extension in TYPO3 6.2 because it is using the method arrayDiffAssocRecursive which is located in core/Classes/Utility/ArrayUtility.php since TYPO3 8.
It would also cause troubles in TYPO3 7.

Here the links to the TYPO3 API for the location of arrayDiffAssocRecursive() method:
TYPO3 6.2 -> https://api.typo3.org/typo3cms/62/html/class_t_y_p_o3_1_1_c_m_s_1_1_core_1_1_utility_1_1_general_utility.html#ad7aece3c8cda4d6b831211364d86d7bc
TYPO3 7 -> https://api.typo3.org/typo3cms/7/html/class_t_y_p_o3_1_1_c_m_s_1_1_core_1_1_utility_1_1_general_utility.html#ad7aece3c8cda4d6b831211364d86d7bc
TYPO3 8: -> https://api.typo3.org/typo3cms/8/html/class_t_y_p_o3_1_1_c_m_s_1_1_core_1_1_utility_1_1_array_utility.html#ad7aece3c8cda4d6b831211364d86d7bc

**Comment by kszymukowicz** [comment]
You right about TYPO3 6.2 but you are not right about TYPO3 7.6  - ArrayUtility.php is there also. 
The function getQueryArguments() is exactly the same for TYPO3 7.6 / 8.7 / 9.0.
Therefore I decided to not support TYPO3 6.2 with xclass. Anyway for this version you can apply path from Resources/Private/Patches/ContentObjectRenderer_TYPO3_6.2.patch
