### ISSUE TITLE
Usage of ArrayUtility without use statement

### ISSUE THREAD

**Issue by wazum** [sourcebroker/urlguard#4]
Using ArrayUtility in urlguard/Classes/Frontend/ContentObject/ContentObjectRenderer.php without using `use TYPO3\CMS\Core\Utility\ArrayUtility;` leads to a fatal error `Class 'SourceBroker\Urlguard\Frontend\ContentObject\ArrayUtility' not found` of course.

**Comment by kszymukowicz** [comment]
You right! I did not noticed that because I am using always composer patches.
Fixed in 0.2.1.
