### ISSUE TITLE
The provided 6.2 patch does not change the composer.json reqs

### ISSUE THREAD

**Issue by DrFelder** [sourcebroker/urlguard#6]
Expected behaviour:
The patch changes the composer.json so that the package can actually be installed.

**Comment by kszymukowicz** [comment]
Sry. You must modify your composer.json yourself. 
I can not expect that all users of TYPO3 use composer.

If you want I can guide you how to do it.

**Comment by DrFelder** [comment]
Do you accept MRs? I changed the extension to be 6.2 comp. again

**Comment by kszymukowicz** [comment]
Sorry but I do not understand what you mean.

**Comment by DrFelder** [comment]
Do you accept merge requests? I changed the extension to be 6.2 compatible again

**Comment by kszymukowicz** [comment]
And where is your PR ?

**Comment by DrFelder** [comment]
It was a general question, I need to test the functionality first

**Comment by kszymukowicz** [comment]
Sry :) Sure. I accept.

**Comment by DrFelder** [comment]
pretty much fixed by https://github.com/sourcebroker/urlguard/pull/7
