### ISSUE TITLE
This should be a TYPO3 core feature

### ISSUE THREAD

**Issue by baschny** [sourcebroker/urlguard#8]
Would you mind in making a patch to include this nice functionality in a future TYPO3 Core version?

**Comment by kszymukowicz** [comment]
Yeap. I will try to find some time on upcoming weekends.

**Comment by geri777** [comment]
I think this is rather a Typo3 Bug, not a missing feature. This has never been a problem with RealURL. It's even likely that this bug can be used to inject harmful code/urls into the website.

**Comment by kszymukowicz** [comment]
Closing this issue as probably https://github.com/b13/trusted-url-params will be part of core soon.
